apiVersion: argoproj.io/v1alpha1
kind: Application
metadata: 
  name: root-app
  namespace: argocd 

spec:
  project: default
  source:
    repoURL: 
    targetRevision: main
    path: 
  destination:
    server: 
    namespace: argocd
  syncPolicy: 
    automated:
      prune: true
      selfHeal: true
