apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: frontend-team
  namespace: argocd
spec:
  description: This is Frontend Team Project
  sourceRepos: 
    - https://github.com/SUNILCHOUHA/k8s-practice.git 
  destinations:
    - namespace: frontend
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  namespaceResourceWhitelist: 
    - group: "*"
      kind: "*"
  roles:
    - name: frondend-admins
      description: Admins for forntend team
      policies:
        - p, proj:frontend-team:frontend-admins, application, *, frontend-team/*, allow
